name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: production
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v2
    - name: Launch tests
      uses: ./.github/workflows/test-branch.yml
    - run: yarn build
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
