name: Deploy
on:
  push:
    branches: [ release ]
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: production
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: yarn install
    - run: yarn test
    - run: yarn build
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
