name: Validate PR
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: yarn install
    - run: yarn test
    - name: Coverage Diff
      uses: greatwizard/coverage-diff-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
